services:
  postgres:
    image: postgres:15-alpine
    container_name: device-management-postgres
    environment:
      POSTGRES_DB: devices_db
      POSTGRES_USER: devices_user
      POSTGRES_PASSWORD: devices_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - device-management-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devices_user -d devices_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: devices-management-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: devices_db
      DB_USERNAME: devices_user
      DB_PASSWORD: devices_pass
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - device-management-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:

networks:
  device-management-network:
    driver: bridge