services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - device-management-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devices_user -d devices_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  device-management-network:
    driver: bridge